Add feature to unassign volunteer
AY2425S1-CS2103T-W12-2/tp pull request #84
Opened 2024-10-17 15:19 UTC by ttzuche

Partially handles #70 #71 #72 

- Added a new command `unassign` to VolunSync
- If volunteer is already unassigned or not involved in the event, a `CommandException` is thrown with the message:  
  `Error: Volunteer is not assigned to this event! `

### Changes:
- Added new class `UnassignCommand`:
  - Retrieve event and volunteer by index.
  - Check for valid indices for both volunteer and event.
  - Unassign volunteer and event only if they are assigned.

### Example Usage:
` unassign v/1 /e/2 `

### Behavior:
- When given invalid index:
    The possible errors are
  - ` Error: The volunteer index provided is invalid `
  - ` Error: The event index provided is invalid `
- On unsuccessful unassignment:  
  ` Error: Volunteer is not assigned to this event! `
- On successful unassignment:  
  ` Volunteer unassigned successfully! `

2024-10-17 17:52 UTC, Fluffykan requested changes
LGTM, just need to make UnassignCommandParser implement Parser&lt;UnassignCommand&gt;

2024-10-17 17:52 UTC, Fluffykan commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
> +        requireAllNonNull(model);
I think this cld just use requireNonNull(model), but no big issue even if its left as is.

2024-10-17 17:52 UTC, Fluffykan commented on src/main/java/seedu/address/logic/parser/UnassignCommandParser.java
> +public class UnassignCommandParser {
This class should implement Parser&lt;UnassignCommand&gt;

2024-10-17 19:20 UTC, keerthigkaarthik requested changes

2024-10-17 19:20 UTC, keerthigkaarthik commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
> +        v.removeEvent(e.getName().toString());
Would it be better to do this inside address book instead? For the other commands, we don't do the actual logic inside execute itself.

2024-10-17 19:20 UTC, keerthigkaarthik commented on src/main/java/seedu/address/model/event/Event.java
> +    public boolean removeVolunteer(String removedVolunteer) {
Should probably call this unassign instead. Same for all other 'remove'.

2024-10-18 11:41 UTC, Fluffykan approved these changes
LGTM

2024-10-18 17:11 UTC, keerthigkaarthik approved these changes

2024-10-18 18:16 UTC, merged